// Ported from ChallengeType.java
// 1-to-1 port from Java
const ChallengeType = {
    COMPLETE_MISSION_TIME: 'COMPLETE_MISSION_TIME',
    USE_ABILITIES_COUNT: 'USE_ABILITIES_COUNT',
    USE_SPECIFIC_ABILITY: 'USE_SPECIFIC_ABILITY',
    CAPTURE_PLANETS: 'CAPTURE_PLANETS',
    WIN_WITHOUT_LOSING_PLANET: 'WIN_WITHOUT_LOSING_PLANET',
    WIN_WITHOUT_CAPTURING_PLANET_TYPE: 'WIN_WITHOUT_CAPTURING_PLANET_TYPE',
    DONATE_GOLD: 'DONATE_GOLD',
    UNLOCK_ABILITIES: 'UNLOCK_ABILITIES',
    PURCHASE_SPECIFIC_ABILITY: 'PURCHASE_SPECIFIC_ABILITY',
    PURCHASE_ABILITY_UPGRADES: 'PURCHASE_ABILITY_UPGRADES',
    PURCHASE_UPGRADES: 'PURCHASE_UPGRADES',
    WIN_STREAK_DIFFICULTY: 'WIN_STREAK_DIFFICULTY'
};
if (typeof module !== 'undefined') module.exports = ChallengeType;